apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ty7wcgoe0-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-go:224b1e96cd1656067b3c0c66be11ed7cae28776b@sha256:a54c9c0cfb3f9262912ba380d1563ba6cb381f33da146013b302dfda12c26c77
          name: container-image
